# <center>  ETL </br>
#  <center> -- Extraer, Transformar y Cargar --</center>
Se realiza la extracción, transformación y carga de los datos proporcionados en el archivo 'australian_user_reviews.json', una primera aproximación a los datos con lo que se cuenta.

### <center>Importar Librerias</center>

In [78]:
import pandas as pd
import numpy as np
import ast
import json
import funciones
import os

import warnings
warnings.filterwarnings("ignore")

___________________

### <center>Extracción de datos</center>

In [79]:
#Se pasa dirección del archivo json
archivo = os.path.join('..', 'BD', 'australian_user_reviews.json')

with open(archivo, 'r', encoding='utf-8') as f:
    data = f.readlines()

# Se convierten las líneas a registros JSON
registro = [eval(line.strip()) for line in data]

# Se almacena en dataframe
df_reviews = pd.DataFrame(registro)
df_reviews

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."
...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la..."
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l..."
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',..."
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l..."
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',..."

_________________________

In [80]:
# Información de los datos del dataframe
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25799 entries, 0 to 25798
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   25799 non-null  object
 1   user_url  25799 non-null  object
 2   reviews   25799 non-null  object
dtypes: object(3)
memory usage: 604.8+ KB

__________________

### <center>Verificación de tipo de datos</center>

In [81]:
# Se observa nulos y tipos de datos de las columnas
funciones.verificar_tipo_datos(df_reviews)

    Columna              Tipo  NO_nulos_%  Nulos_%  Nulos
0   user_id   [<class 'str'>]       100.0      0.0      0
1  user_url   [<class 'str'>]       100.0      0.0      0
2   reviews  [<class 'list'>]       100.0      0.0      0

______________

### <center>La columna reviews es anidada (es una lista de diccionarios) debemos normalizar la columna, para tener una columna por clave del diccionario </center>

La normalización es un proceso mediante el cual se descomponen datos complejos y anidados, comunes en formato JSON, en un formato tabular más manejable.

Se utiliza la función pd.json_normalize() de la biblioteca Pandas en Python para normalizar la columna 'reviews' de un DataFrame

In [82]:
# Se normaliza la columna
df_reviews_n = pd.json_normalize(registro, record_path=['reviews'], meta=['user_id','user_url'] )

# Se visualiza como quedó desanidado
df_reviews_n

,funny,posted,last_edited,item_id,helpful,recommend,review,user_id,user_url
0,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,,"Posted July 15, 2011.",,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,,"Posted April 21, 2011.",,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,,"Posted June 24, 2014.",,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637,http://steamcommunity.com/id/js41637
4,,"Posted September 8, 2013.",,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637,http://steamcommunity.com/id/js41637
...,...,...,...,...,...,...,...,...,...
59300,,Posted July 10.,,70,No ratings yet,True,a must have classic from steam definitely wort...,76561198312638244,http://steamcommunity.com/profiles/76561198312...
59301,,Posted July 8.,,362890,No ratings yet,True,this game is a perfect remake of the original ...,76561198312638244,http://steamcommunity.com/profiles/76561198312...
59302,1 person found this review funny,Posted July 3.,,273110,1 of 2 people (50%) found this review helpful,True,had so much fun plaing this and collecting res...,LydiaMorley,http://steamcommunity.com/id/LydiaMorley
59303,,Posted July 20.,,730,No ratings yet,True,:D,LydiaMorley,http://steamcommunity.com/id/LydiaMorley
59304,,Posted July 2.,,440,No ratings yet,True,so much fun :D,LydiaMorley,http://steamcommunity.com/id/LydiaMorley

In [83]:
# Se observa nulos
df_reviews_n.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59305 entries, 0 to 59304
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   funny        59305 non-null  object
 1   posted       59305 non-null  object
 2   last_edited  59305 non-null  object
 3   item_id      59305 non-null  object
 4   helpful      59305 non-null  object
 5   recommend    59305 non-null  bool
 6   review       59305 non-null  object
 7   user_id      59305 non-null  object
 8   user_url     59305 non-null  object
dtypes: bool(1), object(8)
memory usage: 3.7+ MB

___________________

### <center>Verificación de registros duplicados </center>

In [84]:
# Cantidad de Duplicados en df_items_n
df_reviews_n.duplicated().sum()

874

In [85]:
# Se elimina de uno de los duplicados, conservando el otro
df_reviews_n = df_reviews_n.drop_duplicates(keep='first')
df_reviews_n

,funny,posted,last_edited,item_id,helpful,recommend,review,user_id,user_url
0,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,,"Posted July 15, 2011.",,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,,"Posted April 21, 2011.",,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,,"Posted June 24, 2014.",,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637,http://steamcommunity.com/id/js41637
4,,"Posted September 8, 2013.",,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637,http://steamcommunity.com/id/js41637
...,...,...,...,...,...,...,...,...,...
59300,,Posted July 10.,,70,No ratings yet,True,a must have classic from steam definitely wort...,76561198312638244,http://steamcommunity.com/profiles/76561198312...
59301,,Posted July 8.,,362890,No ratings yet,True,this game is a perfect remake of the original ...,76561198312638244,http://steamcommunity.com/profiles/76561198312...
59302,1 person found this review funny,Posted July 3.,,273110,1 of 2 people (50%) found this review helpful,True,had so much fun plaing this and collecting res...,LydiaMorley,http://steamcommunity.com/id/LydiaMorley
59303,,Posted July 20.,,730,No ratings yet,True,:D,LydiaMorley,http://steamcommunity.com/id/LydiaMorley
59304,,Posted July 2.,,440,No ratings yet,True,so much fun :D,LydiaMorley,http://steamcommunity.com/id/LydiaMorley

In [86]:
# Se verifican los datos
funciones.verificar_tipo_datos(df_reviews_n)

       Columna              Tipo  NO_nulos_%  Nulos_%  Nulos
0        funny   [<class 'str'>]       100.0      0.0      0
1       posted   [<class 'str'>]       100.0      0.0      0
2  last_edited   [<class 'str'>]       100.0      0.0      0
3      item_id   [<class 'str'>]       100.0      0.0      0
4      helpful   [<class 'str'>]       100.0      0.0      0
5    recommend  [<class 'bool'>]       100.0      0.0      0
6       review   [<class 'str'>]       100.0      0.0      0
7      user_id   [<class 'str'>]       100.0      0.0      0
8     user_url   [<class 'str'>]       100.0      0.0      0

_________________

### <center>Columna 'posted'</center>
<center>Al consultar los datos se ve que se refiere a fechas, se cambiar su formato (str: string) a tipo 'date'con el formato 'YYYY-MM-DD', por lo que se hacen transformaciones</center>

In [87]:
# Se realizan reemplazos de caracteres
df_reviews_n['posted'] = df_reviews_n['posted'].str.replace(',','')
df_reviews_n['posted'] = df_reviews_n['posted'].str.replace('.','')
df_reviews_n['posted'] = df_reviews_n['posted'].str.replace('Posted', '')

# Se verifica que el tipo de dato de la columna sea str
df_reviews_n['posted'] = df_reviews_n['posted'].astype(str)

# Se eliminan espacios al principio y fin del dato
df_reviews_n['posted'] = df_reviews_n['posted'].str.strip()

# Se cambia el formato a datetime, manejando los errores como valores nulos
df_reviews_n['posted'] = pd.to_datetime(df_reviews_n['posted'], errors='coerce')

# Se filtran los registros con fechas no nulas
df_reviews_n = df_reviews_n.dropna(subset=['posted'])

# Se convierten las fechas al formato deseado (año/mes/día) como cadenas de texto
df_reviews_n['posted'] = df_reviews_n['posted'].dt.strftime('%Y/%m/%d')

# Se convierten las fechas nuevamente a tipo datetime después de formatearlas como cadenas
df_reviews_n['posted'] = pd.to_datetime(df_reviews_n['posted'], format='%Y/%m/%d')
df_reviews_n

,funny,posted,last_edited,item_id,helpful,recommend,review,user_id,user_url
0,,2011-11-05,,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,,2011-07-15,,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,,2011-04-21,,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,,2014-06-24,,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637,http://steamcommunity.com/id/js41637
4,,2013-09-08,,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637,http://steamcommunity.com/id/js41637
...,...,...,...,...,...,...,...,...,...
59252,1 person found this review funny,2015-10-14,,730,1 of 1 people (100%) found this review helpful,True,its FUNNNNNNNN,wayfeng,http://steamcommunity.com/id/wayfeng
59255,,2015-10-10,,253980,No ratings yet,True,Awesome fantasy game if you don't mind the gra...,76561198251004808,http://steamcommunity.com/profiles/76561198251...
59265,,2015-10-31,,730,No ratings yet,True,Prettyy Mad Game,72947282842,http://steamcommunity.com/id/72947282842
59267,,2015-12-14,,730,No ratings yet,True,AMAZING GAME 10/10,ApxLGhost,http://steamcommunity.com/id/ApxLGhost
59276,1 person found this review funny,2015-12-29,,369200,1 of 2 people (50%) found this review helpful,True,Why I voted yes? 1. Girl characters have boobs...,76561198267374962,http://steamcommunity.com/profiles/76561198267...

In [88]:
df_reviews_n

,funny,posted,last_edited,item_id,helpful,recommend,review,user_id,user_url
0,,2011-11-05,,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,,2011-07-15,,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,,2011-04-21,,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,,2014-06-24,,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637,http://steamcommunity.com/id/js41637
4,,2013-09-08,,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637,http://steamcommunity.com/id/js41637
...,...,...,...,...,...,...,...,...,...
59252,1 person found this review funny,2015-10-14,,730,1 of 1 people (100%) found this review helpful,True,its FUNNNNNNNN,wayfeng,http://steamcommunity.com/id/wayfeng
59255,,2015-10-10,,253980,No ratings yet,True,Awesome fantasy game if you don't mind the gra...,76561198251004808,http://steamcommunity.com/profiles/76561198251...
59265,,2015-10-31,,730,No ratings yet,True,Prettyy Mad Game,72947282842,http://steamcommunity.com/id/72947282842
59267,,2015-12-14,,730,No ratings yet,True,AMAZING GAME 10/10,ApxLGhost,http://steamcommunity.com/id/ApxLGhost
59276,1 person found this review funny,2015-12-29,,369200,1 of 2 people (50%) found this review helpful,True,Why I voted yes? 1. Girl characters have boobs...,76561198267374962,http://steamcommunity.com/profiles/76561198267...

__________________

### <center>Eliminación de Columnas no necesarias</center>

Se procede a eliminar columnas que se creen no necesarias para el estudio a realizar

In [89]:
#Se eliminan columnas
df_reviews_n = df_reviews_n.drop('funny', axis=1)
df_reviews_n = df_reviews_n.drop('last_edited', axis=1)
df_reviews_n = df_reviews_n.drop('user_url', axis=1)

In [90]:
# Se visualizan los datos limpios
df_reviews_n

,posted,item_id,helpful,recommend,review,user_id
0,2011-11-05,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479
1,2011-07-15,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479
2,2011-04-21,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479
3,2014-06-24,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637
4,2013-09-08,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637
...,...,...,...,...,...,...
59252,2015-10-14,730,1 of 1 people (100%) found this review helpful,True,its FUNNNNNNNN,wayfeng
59255,2015-10-10,253980,No ratings yet,True,Awesome fantasy game if you don't mind the gra...,76561198251004808
59265,2015-10-31,730,No ratings yet,True,Prettyy Mad Game,72947282842
59267,2015-12-14,730,No ratings yet,True,AMAZING GAME 10/10,ApxLGhost
59276,2015-12-29,369200,1 of 2 people (50%) found this review helpful,True,Why I voted yes? 1. Girl characters have boobs...,76561198267374962

________________
______________

En este dataset se incluyen reseñas de juegos hechos por distintos usuarios. Se debe crear la columna 'sentiment_analysis' aplicando análisis de sentimiento con NLP con la siguiente escala: debe tomar el valor '0' si es malo, '1' si es neutral y '2' si es positivo. Esta nueva columna debe reemplazar la de 'user_reviews.review' para facilitar el trabajo de los modelos de machine learning y el análisis de datos. De no ser posible este análisis por estar ausente la reseña escrita, debe tomar el valor de 1.

### <center>Analisis de Sentimiento</center>
- Crear columna 'sentiment_analysis' 
- Reemplazar a 'review'
- Etiquetas:</br>
      - 0: "Malo"</br>
      - 2: "Positivo"</br>
      - 1 o NAN: "Neutral"

In [91]:
#Se verifican datos
funciones.verificar_tipo_datos(df_reviews_n)

,Columna,Tipo,NO_nulos_%,Nulos_%,Nulos
0,posted,[<class 'pandas._libs.tslibs.timestamps.Timest...,100.0,0.0,0
1,item_id,[<class 'str'>],100.0,0.0,0
2,helpful,[<class 'str'>],100.0,0.0,0
3,recommend,[<class 'bool'>],100.0,0.0,0
4,review,[<class 'str'>],100.0,0.0,0
5,user_id,[<class 'str'>],100.0,0.0,0

In [92]:
#Se agrega columna 'sentiment_analysis' y se da valores según columna 'review'
df_reviews_n['sentiment_analysis'] = df_reviews_n['review'].apply(funciones.get_sentimiento)

# Se visualiza el nombre de columnas 5 solo 5 columnas para ver el resultado
df_reviews_n.head()

,posted,item_id,helpful,recommend,review,user_id,sentiment_analysis
0,2011-11-05,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,76561197970982479,1
1,2011-07-15,22200,No ratings yet,True,It's unique and worth a playthrough.,76561197970982479,2
2,2011-04-21,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...,76561197970982479,1
3,2014-06-24,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,js41637,1
4,2013-09-08,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...,js41637,1

In [93]:
# Se elimina la columna review
df_reviews_n = df_reviews_n.drop(columns=['review'])

In [94]:
# Se ve la tabla sin la columna
df_reviews_n

,posted,item_id,helpful,recommend,user_id,sentiment_analysis
0,2011-11-05,1250,No ratings yet,True,76561197970982479,1
1,2011-07-15,22200,No ratings yet,True,76561197970982479,2
2,2011-04-21,43110,No ratings yet,True,76561197970982479,1
3,2014-06-24,251610,15 of 20 people (75%) found this review helpful,True,js41637,1
4,2013-09-08,227300,0 of 1 people (0%) found this review helpful,True,js41637,1
...,...,...,...,...,...,...
59252,2015-10-14,730,1 of 1 people (100%) found this review helpful,True,wayfeng,1
59255,2015-10-10,253980,No ratings yet,True,76561198251004808,2
59265,2015-10-31,730,No ratings yet,True,72947282842,0
59267,2015-12-14,730,No ratings yet,True,ApxLGhost,1
59276,2015-12-29,369200,1 of 2 people (50%) found this review helpful,True,76561198267374962,2

_______________
___________________

### <center>Columna 'recommend'</center>
<center>Tiene como tipo de dato 'bool', se debe cambiar formato para el uso de la API</center>

In [95]:
# Se transforma el tipo de dato de la columna 'recommend' de bool a float
df_reviews_n['recommend'] = df_reviews_n['recommend'].astype(float)
df_reviews_n

,posted,item_id,helpful,recommend,user_id,sentiment_analysis
0,2011-11-05,1250,No ratings yet,1.0,76561197970982479,1
1,2011-07-15,22200,No ratings yet,1.0,76561197970982479,2
2,2011-04-21,43110,No ratings yet,1.0,76561197970982479,1
3,2014-06-24,251610,15 of 20 people (75%) found this review helpful,1.0,js41637,1
4,2013-09-08,227300,0 of 1 people (0%) found this review helpful,1.0,js41637,1
...,...,...,...,...,...,...
59252,2015-10-14,730,1 of 1 people (100%) found this review helpful,1.0,wayfeng,1
59255,2015-10-10,253980,No ratings yet,1.0,76561198251004808,2
59265,2015-10-31,730,No ratings yet,1.0,72947282842,0
59267,2015-12-14,730,No ratings yet,1.0,ApxLGhost,1
59276,2015-12-29,369200,1 of 2 people (50%) found this review helpful,1.0,76561198267374962,2

In [96]:
# Información de los tipos de datos
df_reviews_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48498 entries, 0 to 59276
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   posted              48498 non-null  datetime64[ns]
 1   item_id             48498 non-null  object
 2   helpful             48498 non-null  object
 3   recommend           48498 non-null  float64
 4   user_id             48498 non-null  object
 5   sentiment_analysis  48498 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 2.6+ MB

___________________________

### <center> Terminadas las transformaciones, se guarda en un archivo csv </center>

In [97]:
# Se construye la ruta completa al archivo CSV desde la ubicación del notebook
reviews = os.path.join('..', 'CSV', 'reviews_limpio.csv')

# Se guarda el DataFrame en el archivo CSV
df_reviews_n.to_csv(reviews, index=False, encoding='utf-8')

# Se emite un mensaje que se guardó
print(f'Se guardó el archivo {reviews}')

Se guardó el archivo ..\CSV\reviews_limpio.csv