# <center>  ETL </br>
#  <center> -- Extraer, Transformar y Cargar --</center>
Se realiza la extracción, transformación y carga de los datos proporcionados en el archivo 'output_steam_games.json', una primera aproximación a los datos con lo que se cuenta.

### <center>Importar Librerias</center>

In [67]:
import sys
sys.path.append("PROYECTO_INTEGRADOR_I")

In [68]:
import pandas as pd
import numpy as np
import json
import funciones
import os

***

### <center>Extracción de datos</center>

Se observa que el archivo es de tipo JSON, por lo cual se elige una forma particular para poder abrirlo. Se extraen los datos a un DataFrame.

In [69]:
#Se pasa dirección del archivo json
archivo = os.path.join('..', 'BD', 'output_steam_games.json')

# Se lee cada línea del dataset
registros= []
with open(archivo) as f:
    for line in f.readlines():
        data = json.loads(line)
        registros.append(data)

# Se transfoma en DataFrame
df_game = pd.DataFrame(registros)

***

In [70]:
#Visualización del DataFrame
df_game

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns"
120444,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,NaN,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN

In [71]:
#(Filas, Columnas)
df_game.shape

(120445, 13)

In [72]:
#Nombre de las columnas
df_game.columns

Index(['publisher', 'genres', 'app_name', 'title', 'url', 'release_date',
       'tags', 'reviews_url', 'specs', 'price', 'early_access', 'id',
       'developer'],
      dtype='object')

### <center>Verificación de tipo de datos</center>

In [73]:
#Información de tipo de dato y nulos
df_game.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24083 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   url           32135 non-null  object
 5   release_date  30068 non-null  object
 6   tags          31972 non-null  object
 7   reviews_url   32133 non-null  object
 8   specs         31465 non-null  object
 9   price         30758 non-null  object
 10  early_access  32135 non-null  object
 11  id            32133 non-null  object
 12  developer     28836 non-null  object
dtypes: object(13)
memory usage: 11.9+ MB

In [105]:
# Visualización más detallada de los tipos de datos, nulos y porcentajes por columna
funciones.verificar_tipo_datos(df_game)

        Columna                              Tipo  NO_nulos_%  Nulos_%  Nulos
0        genres                   [<class 'str'>]      100.00     0.00      0
1         title  [<class 'str'>, <class 'float'>]      100.00     0.00      2
2   reviews_url                   [<class 'str'>]      100.00     0.00      0
3         price  [<class 'float'>, <class 'str'>]       95.53     4.47   3199
4       item_id                   [<class 'str'>]      100.00     0.00      0
5     developer  [<class 'str'>, <class 'float'>]       99.51     0.49    350
6  release_year                   [<class 'str'>]      100.00     0.00      0

Se observa valores nulos en algunos registros

***

### <center>Verificación de registros nulos </center>

In [76]:
# Visualización de las filas con todos los campos NaN
filas_nan = df_game[df_game.isnull().all(axis=1)]
filas_nan

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
#Se observa 88310 filas con todo Nan y se decide eliminar dichos registros.
df_game = df_game.dropna(how='all').reset_index(drop=True)
df_game.shape

(32135, 13)

_____________

### <center>Verificación de registros duplicados </center>

In [78]:
#Visualización de registros idem
funciones.mostrar_filas_duplicadas(df_game, 'id')

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
13894,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,"[Single-player, Steam Achievements, Full contr...",59.99,False,612880,Machine Games
14573,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/Wolfe...,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,"[Single-player, Steam Achievements, Full contr...",59.99,False,612880,Machine Games
74,NaN,NaN,NaN,NaN,http://store.steampowered.com/,NaN,NaN,NaN,NaN,19.99,False,NaN,NaN
30961,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,"Rocksteady Studios,Feral Interactive (Mac)"

Se observa que hay dos registros que son iguales, se procede a eliminar uno (13894 y 14573) y el 74 tiene valores nulos y la información que posee es insignificante, se elimina.

In [79]:
# se eliminan los index
df_game.drop(13894, inplace=True)
df_game.drop(74, inplace=True)

In [80]:
#se comprueba la eliminación registro 13894
if 13894 not in df_game.index:
    print("\nEl registro con índice 13894 se ha eliminado correctamente.")
else:
    print("\nEl registro con índice 13894 NO se ha eliminado correctamente.")

El registro con índice 13894 se ha eliminado correctamente.

In [81]:
#se comprueba la eliminación registro 74
if 74 not in df_game.index:
    print("\nEl registro con índice 74 se ha eliminado correctamente.")
else:
    print("\nEl registro con índice 74 NO se ha eliminado correctamente.")

El registro con índice 74 se ha eliminado correctamente.

In [82]:
#Se verificaque queda un ID = NAN
funciones.verificar_tipo_datos(df_game)

,Columna,Tipo,NO_nulos_%,Nulos_%,Nulos
0,publisher,"[<class 'str'>, <class 'float'>]",74.94,25.06,8051
1,genres,"[<class 'list'>, <class 'float'>]",89.79,10.21,3282
2,app_name,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
3,title,"[<class 'str'>, <class 'float'>]",93.62,6.38,2049
4,url,[<class 'str'>],100.00,0.00,0
5,release_date,"[<class 'str'>, <class 'float'>]",93.57,6.43,2066
6,tags,"[<class 'list'>, <class 'float'>]",99.50,0.50,162
7,reviews_url,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
8,specs,"[<class 'list'>, <class 'float'>]",97.92,2.08,669
9,price,"[<class 'float'>, <class 'str'>]",95.71,4.29,1377
10,early_access,[<class 'bool'>],100.00,0.00,0
11,id,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
12,developer,"[<class 'str'>, <class 'float'>]",89.74,10.26,3298

In [83]:
# Se filtra las filas con 'id' nulos
filas_id_nulos = df_game[df_game['id'].isnull()]

# Se muestra el resultado
filas_id_nulos

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
30961,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,"Rocksteady Studios,Feral Interactive (Mac)"

Al observar que el id es NAN, buscamos por titulo = "Batman: Arkham City - Game of the Year Edition"

In [84]:
#Se busca según el título
df_game[df_game['title']=='Batman: Arkham City - Game of the Year Edition']

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
1068,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260/Batma...,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",http://steamcommunity.com/app/200260/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,200260,"Rocksteady Studios,Feral Interactive (Mac)"
30961,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,"Rocksteady Studios,Feral Interactive (Mac)"

In [85]:
#se elimina al comprobar que es igual
df_game.drop(30961, inplace=True)

In [86]:
#Se verifica que no queden nulos en ID
funciones.verificar_tipo_datos(df_game)

,Columna,Tipo,NO_nulos_%,Nulos_%,Nulos
0,publisher,"[<class 'str'>, <class 'float'>]",74.94,25.06,8051
1,genres,"[<class 'list'>, <class 'float'>]",89.79,10.21,3282
2,app_name,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
3,title,"[<class 'str'>, <class 'float'>]",93.62,6.38,2049
4,url,[<class 'str'>],100.00,0.00,0
5,release_date,"[<class 'str'>, <class 'float'>]",93.57,6.43,2066
6,tags,"[<class 'list'>, <class 'float'>]",99.50,0.50,162
7,reviews_url,[<class 'str'>],100.00,0.00,0
8,specs,"[<class 'list'>, <class 'float'>]",97.92,2.08,669
9,price,"[<class 'float'>, <class 'str'>]",95.71,4.29,1377
10,early_access,[<class 'bool'>],100.00,0.00,0
11,id,[<class 'str'>],100.00,0.00,0
12,developer,"[<class 'str'>, <class 'float'>]",89.74,10.26,3298

__________________________________

### <center>Extraer AÑO de lanzamiento del item </center>
### <center>release_date </center>

Se debe crear una nueva columna release_year, que solo contiene el año, y se elimina release_date

In [87]:
# Se crea columna nueva con el año 'release_year'
df_game['release_year'] = df_game['release_date'].apply(funciones.obtener_release_year)

# Se elimina la columna 'release_date'
df_game = df_game.drop('release_date', axis=1)
df_game.head()

,publisher,genres,app_name,title,url,tags,reviews_url,specs,price,early_access,id,developer,release_year
0,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
1,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,False,643980,Secret Level SRL,2018
2,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,False,670290,Poolians.com,2017
3,彼岸领域,"[Action, Adventure, Casual]",弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,彼岸领域,2017
4,NaN,NaN,Log Challenge,NaN,http://store.steampowered.com/app/773570/Log_C...,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,"[Single-player, Full controller support, HTC V...",2.99,False,773570,NaN,Dato no disponible

In [88]:
# Se filtra las filas con 'Dato no disponible' en 'release_year'
registros_no_disponibles = df_game.loc[df_game['release_year'] == 'Dato no disponible']
registros_no_disponibles

,publisher,genres,app_name,title,url,tags,reviews_url,specs,price,early_access,id,developer,release_year
4,NaN,NaN,Log Challenge,NaN,http://store.steampowered.com/app/773570/Log_C...,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,"[Single-player, Full controller support, HTC V...",2.99,False,773570,NaN,Dato no disponible
10,Qucheza,"[Action, Indie, Simulation, Early Access]",Uncanny Islands,Uncanny Islands,http://store.steampowered.com/app/768570/Uncan...,"[Early Access, Action, Indie, Simulation, Surv...",http://steamcommunity.com/app/768570/reviews/?...,[Single-player],NaN,True,768570,Qucheza,Dato no disponible
11,NaN,NaN,Icarus Six Sixty Six,NaN,http://store.steampowered.com/app/724910/Icaru...,[Casual],http://steamcommunity.com/app/724910/reviews/?...,"[Single-player, HTC Vive, Tracked Motion Contr...",Free,False,724910,NaN,Dato no disponible
19,NaN,NaN,After Life VR,NaN,http://store.steampowered.com/app/772590/After...,"[Early Access, Indie, VR]",http://steamcommunity.com/app/772590/reviews/?...,"[Single-player, HTC Vive, Tracked Motion Contr...",4.99,True,772590,NaN,Dato no disponible
20,NaN,NaN,Kitty Hawk,NaN,http://store.steampowered.com/app/640250/Kitty...,"[Early Access, Action, Adventure, Indie, Casual]",http://steamcommunity.com/app/640250/reviews/?...,"[Single-player, Steam Leaderboards, HTC Vive, ...",2.99,True,640250,NaN,Dato no disponible
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32087,"Greyson Richey, Nicholas Lives","[Action, Casual, Indie, Simulation]",Lonely Astronaut,Lonely Astronaut,http://store.steampowered.com/app/755830/Lonel...,"[Casual, Action, Indie, Simulation]",http://steamcommunity.com/app/755830/reviews/?...,[Single-player],NaN,False,755830,"Greyson Richey,Nicholas Lives",Dato no disponible
32088,rechargecomplete,"[Action, Adventure, Indie, Early Access]",RECHARGE COMPLETE,RECHARGE COMPLETE,http://store.steampowered.com/app/708070/RECHA...,"[Early Access, Action, Adventure, Indie]",http://steamcommunity.com/app/708070/reviews/?...,"[Single-player, Steam Achievements]",NaN,True,708070,rechargecomplete,Dato no disponible
32097,Lunar Giant Studios,"[Action, Indie]",Tetrapulse,Tetrapulse,http://store.steampowered.com/app/250440/Tetra...,"[Indie, Action, Co-op]",http://steamcommunity.com/app/250440/reviews/?...,"[Multi-player, Co-op, Shared/Split Screen, Ste...",NaN,False,250440,The Amiable,Dato no disponible
32123,VersoVR,"[Casual, Indie, Simulation, Sports, Early Access]",Cricket Club,Cricket Club,http://store.steampowered.com/app/772180/Crick...,"[Early Access, Indie, Casual, Simulation, Sports]",http://steamcommunity.com/app/772180/reviews/?...,[Single-player],NaN,True,772180,VersoVR,Dato no disponible
32134,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN,Dato no disponible

In [89]:
#Se verifica que no queden nulos en release_year
funciones.verificar_tipo_datos(df_game)

,Columna,Tipo,NO_nulos_%,Nulos_%,Nulos
0,publisher,"[<class 'str'>, <class 'float'>]",74.94,25.06,8051
1,genres,"[<class 'list'>, <class 'float'>]",89.79,10.21,3282
2,app_name,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
3,title,"[<class 'str'>, <class 'float'>]",93.62,6.38,2049
4,url,[<class 'str'>],100.00,0.00,0
5,tags,"[<class 'list'>, <class 'float'>]",99.50,0.50,162
6,reviews_url,[<class 'str'>],100.00,0.00,0
7,specs,"[<class 'list'>, <class 'float'>]",97.92,2.08,669
8,price,"[<class 'float'>, <class 'str'>]",95.71,4.29,1377
9,early_access,[<class 'bool'>],100.00,0.00,0
10,id,[<class 'str'>],100.00,0.00,0
11,developer,"[<class 'str'>, <class 'float'>]",89.74,10.26,3298
12,release_year,[<class 'str'>],100.00,0.00,0

In [90]:
# Se obtiene la cantidad de apariciones de cada valor en 'release_year'
conteo_valores = df_game['release_year'].value_counts()

# Se muestra los valores y sus conteos
print(conteo_valores)

release_year
2017                  9517
2016                  6933
2015                  4945
2014                  2832
Dato no disponible    2351
2013                  1551
2012                  1191
2011                   589
2010                   436
2009                   337
2008                   213
2007                   167
2006                   155
2005                   102
2018                    96
2003                    84
2004                    79
2001                    69
1998                    61
1999                    55
2002                    50
1997                    42
2000                    40
1996                    39
1994                    36
1993                    34
1995                    33
1991                    16
1992                    15
1990                    12
1989                    10
1987                     9
1988                     7
1984                     4
1983                     4
1985                     3
1982                     3
1981                     3
2019                     3
1970                     2
1986                     1
2021                     1
1975                     1
1980                     1
Name: count, dtype: int64

_______________________________

### <center>Columna 'genres' </center>
<center>es una lista, hay que separarla</center>

In [91]:
# Se visualiza el dataframe
df_game

,publisher,genres,app_name,title,url,tags,reviews_url,specs,price,early_access,id,developer,release_year
0,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
1,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,False,643980,Secret Level SRL,2018
2,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,False,670290,Poolians.com,2017
3,彼岸领域,"[Action, Adventure, Casual]",弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,彼岸领域,2017
4,NaN,NaN,Log Challenge,NaN,http://store.steampowered.com/app/773570/Log_C...,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,"[Single-player, Full controller support, HTC V...",2.99,False,773570,NaN,Dato no disponible
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32130,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS""",2018
32131,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada,2018
32132,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32133,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns",2017
32134,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN,Dato no disponible

In [92]:
# Se utilizar explode en la columna 'genres' para transformar las listas en filas duplicadas, manteniendo las demás columnas asociadas. 
df_game = df_game.explode('genres')

In [93]:
# Se verifica que no queden nulos en genres
funciones.verificar_tipo_datos(df_game)

,Columna,Tipo,NO_nulos_%,Nulos_%,Nulos
0,publisher,"[<class 'str'>, <class 'float'>]",79.16,20.84,15593
1,genres,"[<class 'str'>, <class 'float'>]",95.61,4.39,3282
2,app_name,"[<class 'str'>, <class 'float'>]",100.00,0.00,2
3,title,"[<class 'str'>, <class 'float'>]",97.26,2.74,2050
4,url,[<class 'str'>],100.00,0.00,0
5,tags,"[<class 'list'>, <class 'float'>]",99.75,0.25,184
6,reviews_url,[<class 'str'>],100.00,0.00,0
7,specs,"[<class 'list'>, <class 'float'>]",98.74,1.26,940
8,price,"[<class 'float'>, <class 'str'>]",95.53,4.47,3346
9,early_access,[<class 'bool'>],100.00,0.00,0
10,id,[<class 'str'>],100.00,0.00,0
11,developer,"[<class 'str'>, <class 'float'>]",95.35,4.65,3478
12,release_year,[<class 'str'>],100.00,0.00,0

In [94]:
# Se eliminan los nulos en genero
df_game = df_game.dropna(subset=['genres'])

In [95]:
# Se visualizan nuevamente los datos en el dataframe
df_game

,publisher,genres,app_name,title,url,tags,reviews_url,specs,price,early_access,id,developer,release_year
0,Kotoshiro,Action,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Casual,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Indie,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Simulation,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Strategy,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32132,Laush Studio,Indie,Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32132,Laush Studio,Racing,Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32132,Laush Studio,Simulation,Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32133,SIXNAILS,Casual,EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns",2017
32133,SIXNAILS,Indie,EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns",2017

____________________

Se procede a eliminar las columnas consideradas no necesarias para el estudio a realizar

In [96]:
# Se elimina las columnas que no necesitamos del Dataframe
df_game = df_game.drop('publisher', axis=1)
df_game = df_game.drop('url', axis=1)
df_game = df_game.drop('app_name', axis=1)
df_game = df_game.drop('specs', axis=1)
df_game = df_game.drop('early_access', axis=1)
df_game = df_game.drop('tags', axis=1)

In [97]:
# Se renombra la columna "id" por "item_id" para su posterior relación con otras tablas
df_game.rename(columns={'id': 'item_id'}, inplace=True)

In [100]:
# Se visualiza el dataframe limpio
df_game

,genres,title,reviews_url,price,item_id,developer,release_year
0,Action,Lost Summoner Kitty,http://steamcommunity.com/app/761140/reviews/?...,4.99,761140,Kotoshiro,2018
0,Casual,Lost Summoner Kitty,http://steamcommunity.com/app/761140/reviews/?...,4.99,761140,Kotoshiro,2018
0,Indie,Lost Summoner Kitty,http://steamcommunity.com/app/761140/reviews/?...,4.99,761140,Kotoshiro,2018
0,Simulation,Lost Summoner Kitty,http://steamcommunity.com/app/761140/reviews/?...,4.99,761140,Kotoshiro,2018
0,Strategy,Lost Summoner Kitty,http://steamcommunity.com/app/761140/reviews/?...,4.99,761140,Kotoshiro,2018
...,...,...,...,...,...,...,...
32132,Indie,Russian Roads,http://steamcommunity.com/app/610660/reviews/?...,1.99,610660,Laush Dmitriy Sergeevich,2018
32132,Racing,Russian Roads,http://steamcommunity.com/app/610660/reviews/?...,1.99,610660,Laush Dmitriy Sergeevich,2018
32132,Simulation,Russian Roads,http://steamcommunity.com/app/610660/reviews/?...,1.99,610660,Laush Dmitriy Sergeevich,2018
32133,Casual,EXIT 2 - Directions,http://steamcommunity.com/app/658870/reviews/?...,4.99,658870,"xropi,stev3ns",2017
32133,Indie,EXIT 2 - Directions,http://steamcommunity.com/app/658870/reviews/?...,4.99,658870,"xropi,stev3ns",2017

In [98]:
# Se verifica los tipos de datos y nulos
funciones.verificar_tipo_datos(df_game)

        Columna                              Tipo  NO_nulos_%  Nulos_%  Nulos
0        genres                   [<class 'str'>]      100.00     0.00      0
1         title  [<class 'str'>, <class 'float'>]      100.00     0.00      2
2   reviews_url                   [<class 'str'>]      100.00     0.00      0
3         price  [<class 'float'>, <class 'str'>]       95.53     4.47   3199
4       item_id                   [<class 'str'>]      100.00     0.00      0
5     developer  [<class 'str'>, <class 'float'>]       99.51     0.49    350
6  release_year                   [<class 'str'>]      100.00     0.00      0

In [107]:
# Se contabiliza la aparición de cada valor que toma la columna 'price'
conteo_publisher = df_game['price'].value_counts()
conteo_publisher

price
4.99                         9475
9.99                         8692
2.99                         7583
0.99                         6190
1.99                         5623
                             ...
27.49                           1
42.99                           1
14.95                           1
0.5                             1
Free HITMAN™ Holiday Pack       1
Name: count, Length: 150, dtype: int64

In [109]:
# Se reemplaza 'Free To Play' por 0 y se convierte la columna 'price' a tipo float
df_game['price'] = pd.to_numeric(df_game['price'].replace('Free To Play', 0), errors='coerce')

# Reemplazar NaN por 0
df_game['price'] = df_game['price'].fillna(0)

In [110]:
funciones.verificar_tipo_datos(df_game)

        Columna                              Tipo  NO_nulos_%  Nulos_%  Nulos
0        genres                   [<class 'str'>]      100.00     0.00      0
1         title  [<class 'str'>, <class 'float'>]      100.00     0.00      2
2   reviews_url                   [<class 'str'>]      100.00     0.00      0
3         price                 [<class 'float'>]      100.00     0.00      0
4       item_id                   [<class 'str'>]      100.00     0.00      0
5     developer  [<class 'str'>, <class 'float'>]       99.51     0.49    350
6  release_year                   [<class 'str'>]      100.00     0.00      0

________________

### <center> terminada la limpieza se guarda en un archivo csv </center>

In [111]:
# Se construye la ruta completa al archivo CSV desde la ubicación del notebook
game = os.path.join('..', 'CSV', 'games_limpio.csv')

# Se guarda el DataFrame en el archivo CSV
df_game.to_csv(game, index=False, encoding='utf-8')

# Se imprime un mensaje si se guardó correctamente
print(f'Se guardó el archivo {game}')

Se guardó el archivo ..\CSV\games_limpio.csv